print("Hello GitHub!")
print("This is a demo file for GitHub.")
print("I am learning how to use GitHub for version control.")
print("I can make changes to this file and commit them to GitHub.")
print("This is a great way to collaborate with others on coding projects.")